version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodblocal
    container_name: dynamodblocal
    command: "-jar DynamoDBLocal.jar"
    volumes:
      - ./dymanodb-data:/data
    ports:
      - "9000:8000"
    expose:
      - "9000"